#+OPTIONS: toc:nil
* Learning jQuery
In this file we'll be building up a number of examples of building dynamic websites with jQuery. There'll be the typical todo-list and the ilk, but maybe some other things meant to at least be slightly more interesting. These are originally my own notes for getting more familiar with all of this, adapted into a format that maybe-just-maybe will be helpful to others. 

Disclaimer: I don't claim that any of these examples will be particularly perfect idioms, and for now there might be a lot of my own idiosyncrasies.
** Obligatory Todos
We start with the standard and obligatory example of a todo list. We'll have some minimal styling and hopefully everything will look nice. 

Our initial HTML file is going to be pretty simple: we're going to have a text field and a button to start, and when we enter text into the field and click the button then what we entered will be pushed into an ordered list beneath the button and text field. 

#+BEGIN_SRC html :exports code :tangle todo.html
  <!DOCTYPE html>
  <html>
    <head>    
      <link rel="stylesheet" type="text/css" href="todo.css">
      <script type='text/javascript' src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
      <script type='text/javascript' src="todo.js"></script>
    </head>
    <body>
      <input id="todoinput" placeholder="Add an item" type="text">
      <button id="adder">Add an item</button>
      <ol id="todool">
        
      </ol>
    </body>
  </html>
#+END_SRC

Now we have only a single handler in our code, but it's going to be the thing that takes the data from the input and pushes it into the ordered list. The important concepts in this little script are 

   + we need to use our ~$(document).ready(...)~ handler to make sure that we only try to attach the handler after the DOM is loaded
   + we grab everything by id (e.g. ~$("#adder")~) to be as exact as possible, though we could have used more generic traversals since there's only /one/ button, /one/ input, /one/ list
   + we use ~val()~ to grab the text and ~val("...")~ to set the input text back to the empty string at the end
   + we add an item to the end of the ordered list with ~.append~
   + we turn the textual html into a real DOM element that we can insert using ~$(...)~
   + we listen for the ~click~ event on the button

#+BEGIN_SRC js :exports code :tangle todo.js
  $(document).ready(function () {
      $("#adder").on("click", function () {
          var el = $("<li>You added: " + $("#todoinput").val() + "</li>");
          $("#todool").append(el);
          $("#todoinput").val("");
      });
  });
#+END_SRC

and just for kicks let's use letters rather than numbers to label the entries

#+BEGIN_SRC css :exports code :tangle todo.css
  ol {
      list-style-type: lower-alpha;
  }
#+END_SRC

** A Color Grid
   So now we're going to do an odd little page that's going to be a 9x9 table with different colors in the different cells, with the colors changing on each click.

   The first thing we do is include a little HTML file that has a table and little else

   #+BEGIN_SRC html :exports code :tangle ColorGrid.html
     <!DOCTYPE html>
     <html>
       <head>
         <link rel="stylesheet" type="text/css" href="ColorGrid.css">
         <script type='text/javascript' src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
         <script type='text/javascript' src="ColorGrid.js"></script>
       </head>
       <body>
         <table id="ourtable">
         </table>
       </body>
     </html>
   #+END_SRC

   What about the table rows and cells? Well, we're actually going to generate those /programmatically/ so that we're not individually making a large number of items. We're also going to attach the event handlers to the individual cells after we make them.

   This has more or less all the same elements we've seen before, except that we've introduced using ~$(this)~ in order to grab the appropriate DOM element for the scope of our function call. JQuery, under the hood, figures out what ~$(this)~ should be. 

#+BEGIN_SRC js :exports code :tangle ColorGrid.js
  function clickHandler() {
      $(this).toggleClass("clicked");
  }

  $(document).ready( function () {
      var table = $("#ourtable");
      for(var row = 0; row < 3; row++) {
          var tr = $("<tr></tr>");
          for(var col = 0; col <3; col++) {
              var td = $("<td></td>");
              td.on("click", clickHandler);
              tr.append(td);
          }
          table.append(tr);
      }
  });
#+END_SRC

   And we're also going to have our css file that has the classes we need as well. The default color is going to be black and, when clicked, the cell will change to be blue.

#+BEGIN_SRC css :exports code :tangle ColorGrid.css
  td {
      background-color: black;
      width: 50px;
      height: 50px;
  }

  td.clicked {
      background-color: blue;
  }
#+END_SRC
